### ISSUE TITLE
bugs: language switch

### ISSUE THREAD

**Issue by lispc** [fluidex/fluidex.github.io#35]
1 about page: You can visit Chinese about page by first visit https://www.fluidex.io/en/about then select "简体中文" but if you visit https://www.fluidex.io/zh/about directly, 404 found
2 lang switch: eg, you are in https://www.fluidex.io/en/blog/fluidex-architecture/ , you select "简体中文", you will be redirect to blog index page, rather then Chinese version of this article. It is a bug or feature

**Comment by lispc** [comment]
ok https://www.fluidex.io/zh/about/ is valid, while https://www.fluidex.io/zh/about is not valid....

**Comment by rayax86** [comment]
doesn't look like problem 1 still exists, I think the trailing slash is automatically added

**Comment by rayax86** [comment]
problem 2 is definitely an issue. no it's not a feature 😅

**Comment by 0xmountaintop** [comment]
closed by https://github.com/fluidex/fluidex.github.io/pull/39
